import {Platform} from 'react-native';
import color from '../../styles/colors';

export default {
  maincontainer: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  backgroundstyle: {
    flex: 1,
    resizeMode: 'cover',
    flexDirection: 'column',
  },
  toolbar: {
    width: '100%',
    height: 90,
    backgroundColor: '#121212',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
  },
  topBar: {
    width: 30,
    height: 30,
    backgroundColor: '#252525',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 100,
  },
  topLeft: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    height: 34,
    width: 60,
    backgroundColor: '#252525',
    borderRadius: 70,
    marginLeft: -17,
    padding: 7,
  },
  topLeftText: {
    color: 'white',
    fontWeight: '600',
  },
  cryptoText: {
    backgroundColor: '#262626',
    width: 100,
    height: 35,
    padding: 4,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 10,
  },
  coinText: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  toolTxt: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 18,
    marginTop: 25,
  },
  backbtn: {
    width: 40,
    height: 50,
    justifyContent: 'center',
    marginTop: 25,
  },
  morebtn: {
    width: 40,
    height: 50,
    justifyContent: 'center',
  },
  backbtnimg: {
    width: 15,
    height: 15,
    resizeMode: 'contain',
    aspectRatio: 1,
    // marginStart: 10,
    tintColor: '#333333',
  },
  forwardarrowImg: {
    width: 20,
    height: 20,
    resizeMode: 'contain',
    aspectRatio: 1.5,
    marginStart: 10,
    transform: [{rotate: '180deg'}],
    tintColor: '#333333',
  },
  forwardArrowImg: {
    width: 16,
    height: 16,
    resizeMode: 'contain',
    aspectRatio: 0.5,
    marginStart: 10,
    transform: [{rotate: '180deg'}],
    tintColor: '#333333',
  },
  searchBar: {
    height: 48,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#121212',
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 25,
  },
 
 
};
